fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix]
        files: \.py$
        exclude: |
          (?x)^(
            tests/|
            build/|
            dist/|
            \.venv/|
            \.temp/|
            .*/tools_api\.py
          ).*$
        stages: [pre-commit]
      - id: ruff
        name: ruff isort
        args: ["check", "--select", "I", "--fix"]
        files: \.py$
        exclude: |
          (?x)^(
            tests/|
            build/|
            dist/|
            \.venv/|
            \.temp/|
            .*/tools_api\.py
          ).*$
        stages: [pre-commit]
      - id: ruff-format
        name: ruff format
        files: \.py$
        exclude: |
          (?x)^(
            tests/|
            build/|
            dist/|
            \.venv/|
            \.temp/|
            .*/tools_api\.py
          ).*$
        stages: [pre-commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: pyupgrade
        args: [--py312-plus]
        files: \.py$
        stages: [ pre-commit ]
        exclude: |
          (?x)^(
            tests/|
            build/|
            dist/|
            \.venv/|
            \.temp/|
            .*/tools_api\.py
          ).*$
  - repo: local
    hooks:
      - id: ty
        name: ty type check
        entry: uvx ty check --ignore unresolved-import src/
        pass_filenames: false
        always_run: true
        exclude: |
          (?x)^(
            tests/|
            build/|
            dist/|
            \.venv/|
            \.temp/|
            .*Dockerfile$
          ).*$
        language: python
        stages: [pre-commit]
      - id: pytest-unit
        name: pytest unit (fast)
        entry: pytest -vx tests/unit
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pytest-integration
        name: pytest integration
        entry: pytest -vx tests/integration
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: pytest-e2e
        name: pytest e2e
        entry: pytest -vx tests/e2e
        language: system
        pass_filenames: false
        stages: [pre-push]